### ISSUE TITLE
Add BIDSEventReader 

### ISSUE THREAD

**Issue by tyarkoni** [tyarkoni/coda#1]
Look for and handle events.tsv.

**Comment by adelavega** [comment]
In 7dd07e4 I made a first attempt at a events.tsv reader.

The main issue is that there are fundamental differences in how FSL style event files and events.tsv files are structured and read. 

1) In FSL style event files, the value of the amplitude column has already been chosen, whereas in events.tsv it is up to the user to chose it. That is, a user may construct FSL event files in which the amplitude column is another experimental value (i.e. reaction time), and the event reader can be oblivious to this and simply take in that as the amplitude. In contrast, when processing events.tsv, a user must have the ability to specify that a certain column will be the amplitude (e.g. RT, or the value of an extracted feature)

2) There are various ways to describe conditions in events.tsv. A suggested, but optional way (according to BIDS), is to have an optional `trial_type` column that describes which condition each event is from. Thus, the `trial_type` column would get read in and become `condition`

However, it is also possible to have different columns represent different "conditions". For example, in the case of neuroscout, the featurex wrapper will output an events.tsv file w/ many columns for all the various features that were extracted. Thus is this case, we want want each column to represent a different "condition". 

Here are two solutions
1) Require a "trial_type" column. For the feature x example, this would result in a very "long format" and not very human readable events.tsv file, but that would be easily processed by BIDSEventsReader.

The implementation in commit 7dd07e4 looks for a trial_type column, and takes an optional amplitude_column argument which it uses to set the amplitude of events.

2) The alternative is to allow for all columns to be imported as "conditions", and then a "select" transformation can be applied to remove irrelevant columns. This is not currently implemented in the commit. 

Here is an example of how this commit implements the first solution.

events.tsv:
![image](https://cloud.githubusercontent.com/assets/2774448/20775729/08327e62-b722-11e6-89b7-ae5161841f4b.png)

    BIDSEventsReader(amplitude_column = 'amp_col').read('events.tsv')

Results in:
![image](https://cloud.githubusercontent.com/assets/2774448/20775781/48615bca-b722-11e6-90be-293de672b751.png)

This is the same result as using EventReader with following FSL-style event files, cond1:
![image](https://cloud.githubusercontent.com/assets/2774448/20775798/5cded262-b722-11e6-96ad-b074785daa9c.png)

and cond2:
![image](https://cloud.githubusercontent.com/assets/2774448/20775802/656658ba-b722-11e6-8b33-9b1cd12f6ad6.png)

    EventReader(columns=['onset', 'duration', 'amplitude']).read('cond*')


@tyarkoni , any thoughts on whether solution #2 is worth pursuing?

**Comment by tyarkoni** [comment]
Good point. I think we want to (a) emphasize ease of use above code simplicity in this case, and (b) stick to the BIDS spec as closely as possible and not force our own extension on it. So I think we want to implement both approaches you mention, and the logic should be to first check if a `trial_type` column is present (case 1), and if not, then assume that each column is a separate condition (case 2). The default `condition_column` value should probably be set to "trial_type" (and if the passed value is missing from events.tsv, then it gets interpreted like `None`).

That also allows us to change the `amplitude_column` handling to allow a value of `None` (which should be the default). The logic for this column becomes as follows:

1. If `amplitude_column` is set to a value other than `None`, all amplitudes are read from that column.
2. If `amplitude_column` is `None` and `trial_type` is present, all amplitudes are set to 1.
3. If `amplitude_column` is `None` and `trial_type` is missing from events.tsv, all extra columns are recoded as new conditions, where the name of the condition is each column name, and the values are the amplitudes.

I think the above makes it very easy for a user to exert near-total control over how the file is read, while still maintaining sane defaults that will, in probably > 95% of cases, require no explicit changing of the default flags.

**Comment by adelavega** [comment]
Cool, that makes sense. I don't think the code is anywhere near too complicated so I'm not worried about that. 

The `trial_type` column is optional in BIDS so we definitely shouldn't force it. 

And yes, currently, `amplitude_column` defaults to None and condition_column defaults to `trial_type`. Do you suppose if `trial_type` is None, it should ignore any columns named `trial_type`? Wouldn't make much sense to treat that column as one that could have an amplitude value.

**Comment by tyarkoni** [comment]
Yes, that's why the default value for `condition_column` should be 'trial_type' rather than `None`; that way it checks for `trial_type` first and falls back to #2 above only if it's missing. But if a trial_type columns *is* present in events.tsv and the user wants to actively suppress that column information in favor of the extra columns (probably an edge case), then they just manually set it to `None`.

**Comment by tyarkoni** [comment]
Oh, for some reason I thought `condition_column` was set to `None` by default, but I think I confused it with `amplitude_column`. The arguments look good as-is, it's just the logic that needs to be tweaked to handle case 2.

**Comment by adelavega** [comment]
Yep, I gotcha.

**Comment by adelavega** [comment]
I dont think we should worry about this, but for posterity an edge case that the current solution could not handle (but is likely rare), is if we had an events.tsv file w/ `trial_type` column, but we wanted to set the amplitude of each condition to different values.

I suppose we could allow this by allowing `condition_column` to either be a single value or a list (whereas the length matches the number of columns in `trial_type`). However, let's punt this for now.

**Comment by tyarkoni** [comment]
That's not in the spec, so I don't think we need to worry about it. If a user is hell-bent on assigning a different value to each trial_type, they can either (a) manually add an amplitude column to events.tsv, or (b) use the "recode" transformation operation later on.

**Comment by adelavega** [comment]
Oh, one more thing. When you said "look for" event files, should this class just be given a BIDS base dir, and subject, run idm etc? and use pybids to find the file? Or be pointed to a file. 

I would think it would be nice to get away from requiring file names, but it might also be good to be flexible and allow that as well.

**Comment by tyarkoni** [comment]
I think this should be independent of pybids. The pattern should probably be to use pybids to retrieve all the events.tsv files based on subject, run, etc., and then loop over them and pass them to  the `BIDSEventReader`. So I think the way it's implemented right now is fine for the moment.

**Comment by adelavega** [comment]
Okay thats fine. I'll roll it back.

**Comment by tyarkoni** [comment]
Wait, I'm confused... what does it do right now?

**Comment by adelavega** [comment]
Well I *just* pushed a commit to implement that feature (see #2). You can either specify a file or a bids base directory and filtering arguments. But sure I can see why you'd want to keep them apart so I'm happy to remove that.

**Comment by tyarkoni** [comment]
Oh, I see (just took a look at the code). Hmm... well if it's already implemented, we may as well leave it for now. I didn't realize it was already done that way, so I just didn't think it should be a priority. But no harm done if it already supports bids-based lookup, as long as it uses the filename first if that's passed (which it does).

**Comment by adelavega** [comment]
allright, cool. its relatively minor either way.
